name = gateway
env = ${?ENVIRONMENT}

ktor {
  application {
    modules = [ dev.hphil.invoice.gateway.ApplicationKt.module ]
  }
  deployment {
    port = ${SERVICES_GATEWAY_PORT}
  }
}

redis {
  host = ${REDIS_HOST}
  port = ${REDIS_PORT}
  password = ${?REDIS_PASSWORD}
  ssl = ${?REDIS_SSL}
}

services {
  auth {
    baseUrl = ${SERVICES_AUTH_DOMAIN}":"${SERVICES_AUTH_PORT}
  }
  account {
    baseUrl = ${SERVICES_ACCOUNT_DOMAIN}":"${SERVICES_ACCOUNT_PORT}
  }
  catalog {
    baseUrl = ${SERVICES_CATALOG_DOMAIN}":"${SERVICES_CATALOG_PORT}
  }
  invoice {
    baseUrl = ${SERVICES_INVOICE_DOMAIN}":"${SERVICES_INVOICE_PORT}
  }
}

auth {
  service {
    clientId = ${AUTH_SERVICE_CLIENT_ID}
    clientSecret = ${AUTH_SERVICE_CLIENT_SECRET}
  }
  user {
    clientId = ${AUTH_USER_CLIENT_ID}
    clientSecret = ${AUTH_USER_CLIENT_SECRET}
  }
}
