/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedAccountBoundRouteImport } from './routes/_authenticated/_account-bound'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts/index'
import { Route as AuthenticatedAccountBoundItemsRouteImport } from './routes/_authenticated/_account-bound/items'
import { Route as AuthenticatedAccountBoundCustomersRouteImport } from './routes/_authenticated/_account-bound/customers'
import { Route as AuthenticatedAccountBoundInvoicesIndexRouteImport } from './routes/_authenticated/_account-bound/invoices/index'
import { Route as AuthenticatedAccountBoundAccountIndexRouteImport } from './routes/_authenticated/_account-bound/account/index'
import { Route as AuthenticatedAccountBoundItemsNewRouteImport } from './routes/_authenticated/_account-bound/items/new'
import { Route as AuthenticatedAccountBoundItemsItemIdRouteImport } from './routes/_authenticated/_account-bound/items/$itemId'
import { Route as AuthenticatedAccountBoundInvoicesInvoiceIdRouteImport } from './routes/_authenticated/_account-bound/invoices/$invoiceId'
import { Route as AuthenticatedAccountBoundCustomersNewRouteImport } from './routes/_authenticated/_account-bound/customers/new'
import { Route as AuthenticatedAccountBoundCustomersCustomerIdRouteImport } from './routes/_authenticated/_account-bound/customers/$customerId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountBoundRoute =
  AuthenticatedAccountBoundRouteImport.update({
    id: '/_account-bound',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountBoundItemsRoute =
  AuthenticatedAccountBoundItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => AuthenticatedAccountBoundRoute,
  } as any)
const AuthenticatedAccountBoundCustomersRoute =
  AuthenticatedAccountBoundCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAccountBoundRoute,
  } as any)
const AuthenticatedAccountBoundInvoicesIndexRoute =
  AuthenticatedAccountBoundInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedAccountBoundRoute,
  } as any)
const AuthenticatedAccountBoundAccountIndexRoute =
  AuthenticatedAccountBoundAccountIndexRouteImport.update({
    id: '/account/',
    path: '/account/',
    getParentRoute: () => AuthenticatedAccountBoundRoute,
  } as any)
const AuthenticatedAccountBoundItemsNewRoute =
  AuthenticatedAccountBoundItemsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountBoundItemsRoute,
  } as any)
const AuthenticatedAccountBoundItemsItemIdRoute =
  AuthenticatedAccountBoundItemsItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => AuthenticatedAccountBoundItemsRoute,
  } as any)
const AuthenticatedAccountBoundInvoicesInvoiceIdRoute =
  AuthenticatedAccountBoundInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedAccountBoundRoute,
  } as any)
const AuthenticatedAccountBoundCustomersNewRoute =
  AuthenticatedAccountBoundCustomersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAccountBoundCustomersRoute,
  } as any)
const AuthenticatedAccountBoundCustomersCustomerIdRoute =
  AuthenticatedAccountBoundCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedAccountBoundCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedAccountBoundRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/customers': typeof AuthenticatedAccountBoundCustomersRouteWithChildren
  '/items': typeof AuthenticatedAccountBoundItemsRouteWithChildren
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/customers/$customerId': typeof AuthenticatedAccountBoundCustomersCustomerIdRoute
  '/customers/new': typeof AuthenticatedAccountBoundCustomersNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedAccountBoundInvoicesInvoiceIdRoute
  '/items/$itemId': typeof AuthenticatedAccountBoundItemsItemIdRoute
  '/items/new': typeof AuthenticatedAccountBoundItemsNewRoute
  '/account/': typeof AuthenticatedAccountBoundAccountIndexRoute
  '/invoices/': typeof AuthenticatedAccountBoundInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedAccountBoundRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/customers': typeof AuthenticatedAccountBoundCustomersRouteWithChildren
  '/items': typeof AuthenticatedAccountBoundItemsRouteWithChildren
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/customers/$customerId': typeof AuthenticatedAccountBoundCustomersCustomerIdRoute
  '/customers/new': typeof AuthenticatedAccountBoundCustomersNewRoute
  '/invoices/$invoiceId': typeof AuthenticatedAccountBoundInvoicesInvoiceIdRoute
  '/items/$itemId': typeof AuthenticatedAccountBoundItemsItemIdRoute
  '/items/new': typeof AuthenticatedAccountBoundItemsNewRoute
  '/account': typeof AuthenticatedAccountBoundAccountIndexRoute
  '/invoices': typeof AuthenticatedAccountBoundInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_account-bound': typeof AuthenticatedAccountBoundRouteWithChildren
  '/_authenticated/_account-bound/customers': typeof AuthenticatedAccountBoundCustomersRouteWithChildren
  '/_authenticated/_account-bound/items': typeof AuthenticatedAccountBoundItemsRouteWithChildren
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/_account-bound/customers/$customerId': typeof AuthenticatedAccountBoundCustomersCustomerIdRoute
  '/_authenticated/_account-bound/customers/new': typeof AuthenticatedAccountBoundCustomersNewRoute
  '/_authenticated/_account-bound/invoices/$invoiceId': typeof AuthenticatedAccountBoundInvoicesInvoiceIdRoute
  '/_authenticated/_account-bound/items/$itemId': typeof AuthenticatedAccountBoundItemsItemIdRoute
  '/_authenticated/_account-bound/items/new': typeof AuthenticatedAccountBoundItemsNewRoute
  '/_authenticated/_account-bound/account/': typeof AuthenticatedAccountBoundAccountIndexRoute
  '/_authenticated/_account-bound/invoices/': typeof AuthenticatedAccountBoundInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/customers'
    | '/items'
    | '/accounts/'
    | '/customers/$customerId'
    | '/customers/new'
    | '/invoices/$invoiceId'
    | '/items/$itemId'
    | '/items/new'
    | '/account/'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/customers'
    | '/items'
    | '/accounts'
    | '/customers/$customerId'
    | '/customers/new'
    | '/invoices/$invoiceId'
    | '/items/$itemId'
    | '/items/new'
    | '/account'
    | '/invoices'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/_account-bound'
    | '/_authenticated/_account-bound/customers'
    | '/_authenticated/_account-bound/items'
    | '/_authenticated/accounts/'
    | '/_authenticated/_account-bound/customers/$customerId'
    | '/_authenticated/_account-bound/customers/new'
    | '/_authenticated/_account-bound/invoices/$invoiceId'
    | '/_authenticated/_account-bound/items/$itemId'
    | '/_authenticated/_account-bound/items/new'
    | '/_authenticated/_account-bound/account/'
    | '/_authenticated/_account-bound/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_account-bound': {
      id: '/_authenticated/_account-bound'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAccountBoundRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_account-bound/items': {
      id: '/_authenticated/_account-bound/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AuthenticatedAccountBoundItemsRouteImport
      parentRoute: typeof AuthenticatedAccountBoundRoute
    }
    '/_authenticated/_account-bound/customers': {
      id: '/_authenticated/_account-bound/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedAccountBoundCustomersRouteImport
      parentRoute: typeof AuthenticatedAccountBoundRoute
    }
    '/_authenticated/_account-bound/invoices/': {
      id: '/_authenticated/_account-bound/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedAccountBoundInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedAccountBoundRoute
    }
    '/_authenticated/_account-bound/account/': {
      id: '/_authenticated/_account-bound/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountBoundAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountBoundRoute
    }
    '/_authenticated/_account-bound/items/new': {
      id: '/_authenticated/_account-bound/items/new'
      path: '/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof AuthenticatedAccountBoundItemsNewRouteImport
      parentRoute: typeof AuthenticatedAccountBoundItemsRoute
    }
    '/_authenticated/_account-bound/items/$itemId': {
      id: '/_authenticated/_account-bound/items/$itemId'
      path: '/$itemId'
      fullPath: '/items/$itemId'
      preLoaderRoute: typeof AuthenticatedAccountBoundItemsItemIdRouteImport
      parentRoute: typeof AuthenticatedAccountBoundItemsRoute
    }
    '/_authenticated/_account-bound/invoices/$invoiceId': {
      id: '/_authenticated/_account-bound/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedAccountBoundInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedAccountBoundRoute
    }
    '/_authenticated/_account-bound/customers/new': {
      id: '/_authenticated/_account-bound/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AuthenticatedAccountBoundCustomersNewRouteImport
      parentRoute: typeof AuthenticatedAccountBoundCustomersRoute
    }
    '/_authenticated/_account-bound/customers/$customerId': {
      id: '/_authenticated/_account-bound/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedAccountBoundCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedAccountBoundCustomersRoute
    }
  }
}

interface AuthenticatedAccountBoundCustomersRouteChildren {
  AuthenticatedAccountBoundCustomersCustomerIdRoute: typeof AuthenticatedAccountBoundCustomersCustomerIdRoute
  AuthenticatedAccountBoundCustomersNewRoute: typeof AuthenticatedAccountBoundCustomersNewRoute
}

const AuthenticatedAccountBoundCustomersRouteChildren: AuthenticatedAccountBoundCustomersRouteChildren =
  {
    AuthenticatedAccountBoundCustomersCustomerIdRoute:
      AuthenticatedAccountBoundCustomersCustomerIdRoute,
    AuthenticatedAccountBoundCustomersNewRoute:
      AuthenticatedAccountBoundCustomersNewRoute,
  }

const AuthenticatedAccountBoundCustomersRouteWithChildren =
  AuthenticatedAccountBoundCustomersRoute._addFileChildren(
    AuthenticatedAccountBoundCustomersRouteChildren,
  )

interface AuthenticatedAccountBoundItemsRouteChildren {
  AuthenticatedAccountBoundItemsItemIdRoute: typeof AuthenticatedAccountBoundItemsItemIdRoute
  AuthenticatedAccountBoundItemsNewRoute: typeof AuthenticatedAccountBoundItemsNewRoute
}

const AuthenticatedAccountBoundItemsRouteChildren: AuthenticatedAccountBoundItemsRouteChildren =
  {
    AuthenticatedAccountBoundItemsItemIdRoute:
      AuthenticatedAccountBoundItemsItemIdRoute,
    AuthenticatedAccountBoundItemsNewRoute:
      AuthenticatedAccountBoundItemsNewRoute,
  }

const AuthenticatedAccountBoundItemsRouteWithChildren =
  AuthenticatedAccountBoundItemsRoute._addFileChildren(
    AuthenticatedAccountBoundItemsRouteChildren,
  )

interface AuthenticatedAccountBoundRouteChildren {
  AuthenticatedAccountBoundCustomersRoute: typeof AuthenticatedAccountBoundCustomersRouteWithChildren
  AuthenticatedAccountBoundItemsRoute: typeof AuthenticatedAccountBoundItemsRouteWithChildren
  AuthenticatedAccountBoundInvoicesInvoiceIdRoute: typeof AuthenticatedAccountBoundInvoicesInvoiceIdRoute
  AuthenticatedAccountBoundAccountIndexRoute: typeof AuthenticatedAccountBoundAccountIndexRoute
  AuthenticatedAccountBoundInvoicesIndexRoute: typeof AuthenticatedAccountBoundInvoicesIndexRoute
}

const AuthenticatedAccountBoundRouteChildren: AuthenticatedAccountBoundRouteChildren =
  {
    AuthenticatedAccountBoundCustomersRoute:
      AuthenticatedAccountBoundCustomersRouteWithChildren,
    AuthenticatedAccountBoundItemsRoute:
      AuthenticatedAccountBoundItemsRouteWithChildren,
    AuthenticatedAccountBoundInvoicesInvoiceIdRoute:
      AuthenticatedAccountBoundInvoicesInvoiceIdRoute,
    AuthenticatedAccountBoundAccountIndexRoute:
      AuthenticatedAccountBoundAccountIndexRoute,
    AuthenticatedAccountBoundInvoicesIndexRoute:
      AuthenticatedAccountBoundInvoicesIndexRoute,
  }

const AuthenticatedAccountBoundRouteWithChildren =
  AuthenticatedAccountBoundRoute._addFileChildren(
    AuthenticatedAccountBoundRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountBoundRoute: typeof AuthenticatedAccountBoundRouteWithChildren
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountBoundRoute: AuthenticatedAccountBoundRouteWithChildren,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
