name = invoice
env = ${?ENVIRONMENT}

ktor {
  application {
    modules = [ dev.hphil.invoice.invoice.ApplicationKt.module ]
  }
  deployment {
    port = ${SERVICES_INVOICE_PORT}
  }
}

database {
  jdbcUrl = ${DATABASE_JDBC_URL}
  username = ${DATABASE_USERNAME}
  password = ${DATABASE_PASSWORD}
  driverClassName = ${?DATABASE_DRIVER_CLASS_NAME}
  maximumPoolSize = ${?DATABASE_MAXIMUM_POOL_SIZE}
  minimumIdle = ${?DATABASE_MINIMUM_IDLE}
  isAutoCommit = ${?DATABASE_AUTO_COMMIT}
  transactionIsolation = ${?DATABASE_TRANSACTION_ISOLATION}
}

services {
  auth {
    baseUrl = ${SERVICES_AUTH_DOMAIN}":"${SERVICES_AUTH_PORT}
  }
  account {
    baseUrl = ${SERVICES_ACCOUNT_DOMAIN}":"${SERVICES_ACCOUNT_PORT}
  }
  catalog {
    baseUrl = ${SERVICES_CATALOG_DOMAIN}":"${SERVICES_CATALOG_PORT}
  }
  invoice {
    baseUrl = ${SERVICES_INVOICE_DOMAIN}":"${SERVICES_INVOICE_PORT}
  }
}

auth {
  service {
    clientId = ${AUTH_SERVICE_CLIENT_ID}
    clientSecret = ${AUTH_SERVICE_CLIENT_SECRET}
  }
}
